name: csv_plus
description: >
  Complete, high-performance CSV package for Dart.
  Read, write, stream, manipulate, validate — with maximum speed and type safety.
version: 0.0.1
repository: https://github.com/csv-plus/csv_plus

environment:
  sdk: ^3.5.0

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
